In [49]:
import numpy as np

In [50]:
list1 = [1, 2, 3, 4, 5]
print(list1)

[1, 2, 3, 4, 5]


In [51]:
arr1 = np.array(list1)
print(arr1)

[1 2 3 4 5]


In [52]:
two_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
two_arr = np.array(two_list)
print(two_arr)
print(two_arr.shape)  #大小  
print(two_arr.dtype)  #数据类型
print(two_arr.size)  #元素个数
print(two_arr.ndim)  #维度

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
int64
9
2


In [53]:
#转成二维
t = np.arange(24)
print(t)
t1 = t.reshape((4, 6))
print(t1)
print(t1.shape)
print(t1.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)
2


In [54]:
#转成三维
t2 = t.reshape(2, 3, 4)
print(t2)
print(t2.shape)
print(t2.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
3


# NumPy的数据类型

In [55]:
import random

f = np.array([1, 2, 3, 4, 5], dtype=np.int16)
print(f.itemsize)
print(f.dtype)

2
int16


In [56]:
#调整数据类型
f1 = f.astype(np.int64)
print(f1.itemsize)
print(f1.dtype)

8
int64


# 数组的运算

In [57]:
a = np.arange(24).reshape(6, 4)
b = np.arange(100, 124).reshape(6, 4)
print(a)
print(b)
print('-' * 50)
print(a + b)
print('-' * 50)
print(a * b)  #对应位置相乘，不是矩阵乘法

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]
 [116 117 118 119]
 [120 121 122 123]]
--------------------------------------------------
[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
--------------------------------------------------
[[   0  101  204  309]
 [ 416  525  636  749]
 [ 864  981 1100 1221]
 [1344 1469 1596 1725]
 [1856 1989 2124 2261]
 [2400 2541 2684 2829]]


In [58]:
#一维数组和二维数组的运算
t1 = np.arange(24).reshape(4, 6)
t2 = np.arange(6).reshape(1, 6)
print(t1)
print(t2)
print('-' * 50)
print(t1 + t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[0 1 2 3 4 5]]
--------------------------------------------------
[[ 0  2  4  6  8 10]
 [ 6  8 10 12 14 16]
 [12 14 16 18 20 22]
 [18 20 22 24 26 28]]


# 练习轴

In [59]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
print(a.sum(axis=0))  #按列求和
print(a.sum(axis=1))  #按行求和

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]


# 索引和切片

In [60]:
a = np.arange(10)
print(a[0], a)
print(a[2:])
print(a[2:8:2])
b = a.reshape(2, 5)
print('-' * 50)
print(b)
print('-' * 50)
print(b[0, 2])
print('-' * 50)
print(b[[0, 1], [0, 2]])  #取出第0行和第1行的第0列和第2列的值
b[:, 1]

0 [0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 4 6]
--------------------------------------------------
[[0 1 2 3 4]
 [5 6 7 8 9]]
--------------------------------------------------
2
--------------------------------------------------
[0 7]


array([1, 6])

In [61]:
t = np.arange(24).reshape(4, 6)
print(t)
print('-' * 50)
# t[(t>2)&(t<6)]=0
# t[(t<2)|(t>6)]=0
# t[~(t>6)]=0
t = t.clip(10, 18)  #把小于10的替换成10，大于18的替换成18
print(t)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------------------------------------
[[10 10 10 10 10 10]
 [10 10 10 10 10 11]
 [12 13 14 15 16 17]
 [18 18 18 18 18 18]]


# 转置和轴滚动

In [62]:
# a = np.arange(12).reshape(3, 4)
# print(f'原数组：\n{a}')
# print(f'转置数组：\n{a.T}')
# print(f'二维轴交换数组：\n{a.swapaxes(0, 1)}')
# print('-'*50)
b = np.arange(24).reshape(2,3,4)
print(f'原数组：\n{b.shape}\n{b}')
b1=np.swapaxes(b,0,1) 
print(f'三维轴交换数组：\n{b1.shape}\n{b1}')  #轴0和轴1交换

原数组：
(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
三维轴交换数组：
(3, 2, 4)
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]


In [63]:
a=np.ones((3,4,5,6))
b=np.rollaxis(a,3,1) 
b.shape

(3, 6, 4, 5)

In [65]:
np.rollaxis(b,1,4).shape#轴滚动到4位置之前，即轴3和轴1交换

(3, 4, 5, 6)